In [ ]:
# Autor: Rodrigo Terán Hernández A01704108
# Última versión: 6/04/2025

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [1]:
import pandas as pd
df_uncleaned=pd.read_csv('cardekho.csv')
df_uncleaned

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.40,1248.0,74,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14,1498.0,103.52,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.70,1497.0,78,5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.00,1396.0,90,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.10,1298.0,88.2,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai i20 Magna,2013,320000,110000,Petrol,Individual,Manual,First Owner,18.50,1197.0,82.85,5.0
8124,Hyundai Verna CRDi SX,2007,135000,119000,Diesel,Individual,Manual,Fourth & Above Owner,16.80,1493.0,110,5.0
8125,Maruti Swift Dzire ZDi,2009,382000,120000,Diesel,Individual,Manual,First Owner,19.30,1248.0,73.9,5.0
8126,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57,1396.0,70,5.0
8127,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57,1396.0,70,5.0

In [2]:
# Drop rows with any missing values
df_cleaned = df_uncleaned.dropna()

# Reset index after dropping rows
df_cleaned = df_cleaned.reset_index(drop=True)

numeric_cols = ['year', 'selling_price', 'km_driven', 'mileage(km/ltr/kg)', 'engine', 'max_power', 'seats']

for col in numeric_cols:
    df_cleaned[col] = pd.to_numeric(df_cleaned[col], errors='coerce')  # Convert, setting errors to NaN

# Drop rows that had invalid values
df_cleaned = df_cleaned.dropna()

# Reset index again
df_cleaned = df_cleaned.reset_index(drop=True)

valid_values = {
    'transmission': ['Automatic', 'Manual'],
    'owner': ['Second Owner', 'Third Owner', 'First Owner', 'Fourth & Above Owner'],
    'seller_type': ['Individual', 'Dealer', 'Trustmark Dealer'],
    'fuel': ['Petrol', 'LPG', 'Diesel', 'CNG']
}

# Remove rows where any of the categorical columns contain invalid values
for col, valid_list in valid_values.items():
    df_cleaned = df_cleaned[df_cleaned[col].isin(valid_list)]

# Reset index after filtering
df_cleaned = df_cleaned.reset_index(drop=True)

In [3]:
df_cleaned

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.40,1248.0,74.00,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14,1498.0,103.52,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.70,1497.0,78.00,5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.00,1396.0,90.00,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.10,1298.0,88.20,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
7896,Hyundai i20 Magna,2013,320000,110000,Petrol,Individual,Manual,First Owner,18.50,1197.0,82.85,5.0
7897,Hyundai Verna CRDi SX,2007,135000,119000,Diesel,Individual,Manual,Fourth & Above Owner,16.80,1493.0,110.00,5.0
7898,Maruti Swift Dzire ZDi,2009,382000,120000,Diesel,Individual,Manual,First Owner,19.30,1248.0,73.90,5.0
7899,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57,1396.0,70.00,5.0
7900,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57,1396.0,70.00,5.0

In [4]:
import os
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(
    df_cleaned,
    test_size=0.2,
    random_state=42,
    shuffle=True
)

In [5]:
test_df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
4913,Honda City 2017-2020 EXi,2007,138000,120000,Petrol,Individual,Manual,Second Owner,17.70,1497.0,78.0,5.0
4900,Ford Figo 1.2P Ambiente MT,2017,370000,40000,Petrol,Individual,Manual,Second Owner,18.16,1196.0,86.8,5.0
2301,Maruti Wagon R LXI BS IV,2012,265000,67998,Petrol,Dealer,Manual,First Owner,18.90,998.0,67.1,5.0
6953,Skoda Octavia Rider 1.9 AT TDI,2008,210000,120000,Diesel,Individual,Manual,Second Owner,18.70,1896.0,66.0,5.0
3528,Maruti Wagon R VXI BS IV,2011,229999,500000,Petrol,Individual,Manual,Second Owner,18.90,998.0,67.1,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
6128,Maruti Wagon R LXI,2006,90000,168000,Petrol,Individual,Manual,Second Owner,18.90,998.0,67.1,5.0
1410,Honda City 2017-2020 GXi,2006,93150,80000,Petrol,Individual,Manual,Second Owner,17.70,1497.0,78.0,5.0
4787,Mahindra Bolero 2011-2019 SLX 2WD BSIII,2016,700000,91182,Diesel,Individual,Manual,First Owner,15.96,2523.0,62.1,7.0
3139,Jeep Wrangler 2016-2019 3.6 4X4,2017,4100000,17000,Petrol,Individual,Automatic,First Owner,9.50,3604.0,280.0,5.0
889,Maruti Swift Dzire VDi,2009,180000,144000,Diesel,Individual,Manual,Second Owner,19.30,1248.0,73.9,5.0

In [6]:
train_features_df = train_df.drop(columns=["selling_price"])  # Remove selling_price column
train_target_df = train_df["selling_price"]  # Store selling_price as target

test_features_df = test_df.drop(columns=["selling_price"])  # Remove selling_price column
test_target_df = test_df["selling_price"]  # Store selling_price as target

# Save the datasets
train_features_df.to_csv("train_features.csv", index=False)
train_target_df.to_csv("train_target.csv", index=False)

test_features_df.to_csv("test_features.csv", index=False)
test_target_df.to_csv("test_target.csv", index=False)

In [8]:
test_target_df

4913     138000
4900     370000
2301     265000
6953     210000
3528     229999
         ...
6128      90000
1410      93150
4787     700000
3139    4100000
889      180000
Name: selling_price, Length: 1581, dtype: int64

In [14]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import joblib

# Columnas numéricas y categóricas
numeric_features = ['year', 'km_driven', 'mileage(km/ltr/kg)', 'engine', 'max_power', 'seats']
categorical_features = ['fuel', 'seller_type', 'transmission', 'owner']

# Preprocesamiento
numeric_transformer = MinMaxScaler()
categorical_transformer = OneHotEncoder(handle_unknown='ignore')

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ]
)

# Modelo con pipeline
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', RandomForestRegressor(random_state=42))
])

# Entrenar modelo
model.fit(train_features_df, train_target_df.values.ravel())

# Predecir
y_pred = model.predict(test_features_df)

# Calcular el MAPE
mape = np.mean(np.abs((test_target_df - y_pred) / test_target_df)) * 100

# Evaluar modelo
# Los precios están en "Indian rupees":

# ------- Mean Absolute Error
# - Indian rupees: 61,865.10​ ₹
# - MXN: 61,865.10 × 0.2389 ≈ 14,789.47 MXN​
print("MAE:", mean_absolute_error(test_target_df, y_pred))

# ------- Mean Squared Error
# - Indian rupees: 13,664,439,025.37 ₹²
# - MXN: 61,865.10 × 0.2389 ≈ 3,264,434,483.16 MXN​²
print("MSE:", mean_squared_error(test_target_df, y_pred))

# ------- R Squared
# R2 Score: 0.9781
print("R2 Score:", r2_score(test_target_df, y_pred))

# ------- Mean Absolute Percentage Error
# MAPE: 14.4%
print(f"MAPE: {mape:.2f}%")

MAE: 61865.09573263033
MSE: 13664439025.372446
R2 Score: 0.9781410391292465
MAPE: 14.40%